stages:
  - sync_with_github

sync_to_github:
  stage: sync_with_github
  image: alpine:latest
  script:
    - set -e  # Exit immediately if a command exits with a non-zero status
    - apk add --no-cache git curl jq
    - git config --global user.email "kittuvelagala@gmail.com"
    - git config --global user.name "krishna reddy velagala"
    - export REPO_NAME=$(basename $CI_PROJECT_PATH)  # Extract just the project name (e.g., coursera-deeplearning-specialization)
    - export GROUP_NAME=$(dirname $CI_PROJECT_PATH | cut -d'/' -f1)  # Extract the group name (e.g., mlengineer)
    - echo "Group Name: $GROUP_NAME"  # Debug output for group name
    - export GITHUB_REPO_URL="https://$GITHUB_USERNAME:$GITHUB_TOKEN@github.com/$GITHUB_USERNAME/$REPO_NAME.git"
    - |
      # Check if the GitHub repository exists; if not, create it
      REPO_CHECK=$(curl -s -o /dev/null -w "%{http_code}
